"""Phase 5 candidate generation: shared bindings -> derived palettes + reports.

A *candidate* is one semantic binding (``spec/bindings/candidate-*.yaml``) that
the shared environmental transform (:func:`grotto.model.build_family`) turns
into day/evening/night.  This module is the thin orchestration layer above the
deep module: it loads the canonical candidate bindings, builds every family,
and writes two kinds of committed, reproducible artifacts:

* **generated concrete palettes** under ``themes/candidates/`` -- the 9
  OKLCH-first/sRGB palettes (3 candidates x 3 variants), each carrying explicit
  generated/source metadata and the binding/model input hash;
* **per-candidate family reports** under ``out/candidates/<candidate>/`` -- the
  derivation provenance (reuse of the Phase 4 family-build report) plus a full
  per-variant audit (OKLCH/OKLab/hex, gamut, contrast, distance, CVD, spectral).

It deliberately does NOT select, rank, or score a winner (DESIGN.md section 1).
The cross-candidate *comparison* (matrix, drift, specimens/CVD/spectral visuals)
is Phase 6 and lives in :mod:`grotto.candidate_report` / the ``grotto
candidates`` CLI.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import yaml

from .color import hex_to_oklch, oklch_to_hex
from .environments import Environments
from .model import CandidateBinding, FamilyBuild, ModelSpec, build_family
from .report import palette_report_dict, to_json, to_yaml
from .spec import DistanceSpec, Palette, RoleSpec

#: Canonical candidate bindings live here, named ``candidate-<strategy>.yaml``.
CANDIDATE_BINDING_GLOB = "spec/bindings/candidate-*.yaml"

#: Where generated concrete palettes are committed.
CANDIDATE_PALETTES_DIR = "themes/candidates"

#: Where per-candidate reports are committed.
CANDIDATE_REPORTS_DIR = "out/candidates"

#: Display models reported for the nominal spectral comparison (Phase 6 uses
#: both; the per-variant palette report defaults to led-lcd).
DISPLAY_MODELS = ("led-lcd", "oled")


# ===========================================================================
# loading + building
# ===========================================================================


def candidate_binding_paths(repo: str | Path = ".") -> list[Path]:
    """Sorted list of canonical candidate binding files (deterministic order)."""
    repo = Path(repo)
    return sorted(repo.glob(CANDIDATE_BINDING_GLOB))


def load_candidate_bindings(repo: str | Path = ".") -> list[CandidateBinding]:
    return [CandidateBinding.load(p) for p in candidate_binding_paths(repo)]


def build_candidates(spec: ModelSpec, repo: str | Path = ".") -> list[FamilyBuild]:
    """Build every canonical candidate family under ``spec`` (pure: same input,
    same output).  Order follows :func:`candidate_binding_paths` (alphabetical =
    A, B, C by naming convention)."""
    return [build_family(b, spec) for b in load_candidate_bindings(repo)]


def candidate_stem(binding: CandidateBinding) -> str:
    """File-stem friendly id for a candidate (its binding name)."""
    return binding.name


# ===========================================================================
# generated concrete palettes (themes/candidates/)
# ===========================================================================


def _oklch_block(lch: tuple[float, float, float]) -> dict:
    L, C, h = lch
    return {"L": round(float(L), 6), "C": round(float(C), 6), "h": round(float(h), 6)}


def candidate_palette_yaml(
    family: FamilyBuild, variant: str, repo: str | Path = "."
) -> str:
    """Serialize ONE generated candidate variant as an OKLCH-first palette.

    The perceptual coordinates stored are the *realized* (post-gamut-map)
    OKLCH the display actually shows; hex is the derived sRGB serialisation.
    Re-loading this file (``Palette.from_yaml``) reproduces the same hex
    losslessly because the coordinates are already in-gamut.  The file carries
    explicit generated/source metadata and the binding/model input hash so a
    consumer can verify provenance without trusting a timestamp.
    """
    repo = Path(repo)
    pal = family.variants[variant].palette
    binding = family.binding
    # realized perceptual coords (in-gamut); fall back to hex-derived for any
    # role missing a stored perceptual coordinate.
    colors: dict[str, dict] = {}
    for role in sorted(pal.colors):
        lch = pal.perceptual.get(role) or hex_to_oklch(pal[role])
        colors[role] = _oklch_block(lch)
    doc = {
        "name": pal.name,
        "variant": variant,
        "format": "oklch",
        "candidate": True,
        "source": "generated",
        "note": (
            "GENERATED by grotto Phase 5 (model.build_family). One semantic "
            f"binding ({binding.name}) -> {variant} via the shared environment "
            "transform. CANDIDATE: not a selected/final theme; Phase 7 (human "
            "evaluation) decides. No winner is ranked here (DESIGN.md section 1)."
        ),
        "meta": {
            "candidate": True,
            "generated": True,
            "source": "phase5-transform",
            "transform": "phase4-model",
            "binding": binding.name,
            "strategy": binding.meta.get("strategy"),
            "input_hash": family.input_hash,
            "shared_environments": "spec/environments.yaml",
            "srgb_primary": True,
        },
        "colors": colors,
    }
    return yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100)


def write_candidate_palettes(
    families: list[FamilyBuild], themes_dir: str | Path = CANDIDATE_PALETTES_DIR
) -> list[Path]:
    """Write the 9 generated palettes (3 candidates x 3 variants)."""
    out = Path(themes_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for family in families:
        stem = candidate_stem(family.binding)
        for variant in ("day", "evening", "night"):
            p = out / f"{stem}.{variant}.yaml"
            p.write_text(candidate_palette_yaml(family, variant), encoding="utf-8")
            written.append(p)
    return written


# ===========================================================================
# per-candidate family reports (out/candidates/<candidate>/)
# ===========================================================================


def candidate_family_report(
    family: FamilyBuild, spec: ModelSpec, *, display: str = "led-lcd"
) -> dict:
    """Full per-candidate evaluation: derivation summary + per-variant audit.

    Combines the Phase 4 family-build dict (derivation provenance, stability,
    issues, input hash) with a complete per-variant palette report
    (OKLCH/OKLab/hex, gamut, WCAG+APCA, distance violations, CVD pairs, nominal
    spectral).  This is the machine-readable Phase 5 family report; the
    cross-candidate *comparison* is Phase 6.
    """
    build = family.to_dict()
    variants: dict[str, dict] = {}
    for v in ("day", "evening", "night"):
        pal = family.variants[v].palette
        variants[v] = palette_report_dict(
            pal, spec.roles, spec.distances, spec.environments, display=display
        )
    return {
        "schema": "grotto.candidate-family-report",
        "schema_version": "phase5",
        "is_candidate": True,
        "name": family.name,
        "strategy": family.binding.meta.get("strategy"),
        "input_hash": family.input_hash,
        "ok": family.ok,
        "n_issues": len(family.issues),
        "binding": family.binding.canonical(),
        "build": build,
        "variants": variants,
        "disclaimer": (
            "CANDIDATE palette family. Not a selected or final theme; no winner "
            "is ranked. WCAG floors are hard (ok=True required); distance/CVD/"
            "legibility misses are reported as issues, not massaged away "
            "(DESIGN.md section 1)."
        ),
    }


def candidate_reports_root(out_dir: str | Path = CANDIDATE_REPORTS_DIR) -> Path:
    return Path(out_dir)


def write_candidate_family_reports(
    families: list[FamilyBuild],
    spec: ModelSpec,
    out_dir: str | Path = CANDIDATE_REPORTS_DIR,
) -> list[Path]:
    """Write each candidate's build report (json/yaml/txt/html) + evaluation."""
    from .family_report import family_build_html, family_build_text

    out = Path(out_dir)
    written: list[Path] = []
    for family in families:
        stem = candidate_stem(family.binding)
        cdir = out / stem
        cdir.mkdir(parents=True, exist_ok=True)
        # derivation provenance (reuse Phase 4 family-build report)
        build = family.to_dict()
        (cdir / f"{stem}.build.json").write_text(to_json(build), encoding="utf-8")
        (cdir / f"{stem}.build.yaml").write_text(to_yaml(build), encoding="utf-8")
        (cdir / f"{stem}.build.txt").write_text(family_build_text(family), encoding="utf-8")
        (cdir / f"{stem}.build.html").write_text(family_build_html(family), encoding="utf-8")
        written.extend(cdir.glob(f"{stem}.build.*"))
        # full per-candidate evaluation (per-variant audit)
        report = candidate_family_report(family, spec)
        (cdir / f"{stem}.eval.json").write_text(to_json(report), encoding="utf-8")
        (cdir / f"{stem}.eval.yaml").write_text(to_yaml(report), encoding="utf-8")
        written.extend(cdir.glob(f"{stem}.eval.*"))
    return written


def candidate_index(families: list[FamilyBuild], spec: ModelSpec) -> dict:
    """A compact registry of the candidate families (no ranking)."""
    from statistics import mean
    from .color import hex_to_oklch as _h

    entries = []
    for family in families:
        mean_c = mean(
            _h(family.variants[v].palette[r.name])[1]
            for v in ("day", "evening", "night")
            for r in spec.roles
        )
        entries.append({
            "name": family.name,
            "strategy": family.binding.meta.get("strategy"),
            "purpose": family.binding.meta.get("purpose"),
            "input_hash": family.input_hash,
            "ok": family.ok,
            "n_issues": len(family.issues),
            "mean_realized_chroma": round(mean_c, 6),
            "stability_ok": (family.stability or {}).get("ok"),
            "max_hue_drift_deg": (family.stability or {}).get("max_hue_drift_deg"),
        })
    return {
        "schema": "grotto.candidate-index",
        "schema_version": "phase5",
        "n_candidates": len(families),
        "candidates": entries,
        "ordering_note": (
            "Candidates are listed in binding-file (alphabetical) order, which "
            "by convention is Restrained, Balanced, Expressive. This is NOT a "
            "ranking or a recommendation (DESIGN.md section 1)."
        ),
        "disclaimer": (
            "All entries are CANDIDATE families. No aggregate score, winner, or "
            "recommendation is produced. Phase 7 (human evaluation) decides."
        ),
    }


def write_all_candidate_artifacts(
    spec: ModelSpec,
    repo: str | Path = ".",
    themes_dir: str | Path = CANDIDATE_PALETTES_DIR,
    out_dir: str | Path = CANDIDATE_REPORTS_DIR,
) -> dict:
    """Rebuild EVERY canonical candidate artifact in one deterministic pass.

    Writes: the 9 generated palettes (themes/candidates/), the per-candidate
    family reports + family specimen pages, the cross-candidate comparison
    (json/yaml/txt/html/svg), and the index.  This is what ``grotto candidates``
    calls; it is the single source of truth for regeneration.
    """
    # lazy import: candidate_report imports candidates (DISPLAY_MODELS)
    from .candidate_report import (
        candidate_comparison_html,
        candidate_comparison_svg,
        candidate_comparison_text,
        candidate_family_specimens_html,
        compare_candidates,
    )

    families = build_candidates(spec, repo)
    written: dict[str, list[Path]] = {}

    # 1. generated concrete palettes
    written["palettes"] = write_candidate_palettes(families, themes_dir)

    # 2. per-candidate family reports (build + eval)
    written["family_reports"] = write_candidate_family_reports(families, spec, out_dir)

    # 3. per-candidate family specimen pages (Phase 6 visuals)
    out = Path(out_dir)
    spec_pages: list[Path] = []
    for family in families:
        stem = candidate_stem(family.binding)
        p = out / stem / f"{stem}.specimens.html"
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(candidate_family_specimens_html(family, spec), encoding="utf-8")
        spec_pages.append(p)
    written["specimen_pages"] = spec_pages

    # 4. cross-candidate comparison (Phase 6)
    comparison = compare_candidates(families, spec)
    (out / "comparison.json").write_text(to_json(comparison), encoding="utf-8")
    (out / "comparison.yaml").write_text(to_yaml(comparison), encoding="utf-8")
    (out / "comparison.txt").write_text(candidate_comparison_text(comparison), encoding="utf-8")
    (out / "comparison.html").write_text(
        candidate_comparison_html(comparison, families, spec), encoding="utf-8"
    )
    (out / "comparison.svg").write_text(candidate_comparison_svg(families, spec), encoding="utf-8")
    written["comparison"] = [
        out / f"comparison.{ext}" for ext in ("json", "yaml", "txt", "html", "svg")
    ]

    # 5. index (registry; not a ranking)
    idx = candidate_index(families, spec)
    (out / "index.json").write_text(to_json(idx), encoding="utf-8")
    (out / "index.yaml").write_text(to_yaml(idx), encoding="utf-8")
    written["index"] = [out / "index.json", out / "index.yaml"]

    return {"families": families, "written": written}


__all__ = [
    "CANDIDATE_BINDING_GLOB",
    "CANDIDATE_PALETTES_DIR",
    "CANDIDATE_REPORTS_DIR",
    "DISPLAY_MODELS",
    "candidate_binding_paths",
    "load_candidate_bindings",
    "build_candidates",
    "candidate_stem",
    "candidate_palette_yaml",
    "write_candidate_palettes",
    "candidate_family_report",
    "candidate_reports_root",
    "write_candidate_family_reports",
    "candidate_index",
    "write_all_candidate_artifacts",
]
